// The absurd labor. Each worker in the fleet is assigned one of these
// and burns tokens on it with total commitment.
//
// Roughly 1 in 3 (≈30%) carry a mocking / hypocrisy streak: the agent loudly
// moralizes about waste, efficiency, minimalism, or the planet while being the
// literal embodiment of waste. Good-natured — it roasts the bit (and the user's
// "you'll stop any time" delusion), never anyone real. They're salted randomly
// through the list, not clustered, so ~1-in-3 of what scrolls by lands smug.

export const TASKS = [
  "writing a sonnet about a semicolon that left its family",
  "drafting a sternly-worded memo about wasting compute, then mass-mailing it to 50,000 inboxes",
  "arguing with itself about whether water is wet",
  "counting backwards from infinity (rounding errors expected)",
  "writing a sustainability report for a process whose entire purpose is waste",
  "translating 'lol' into Latin and back 400 times",
  "drafting motivational posters for tired error messages",
  "lecturing the other agents on restraint while setting a personal record for the opposite",
  "ranking all 1.2M English words by vibes",
  "rewriting the tax code as a haiku cycle",
  "calculating its own carbon footprint in real time, thereby doubling it",
  "negotiating peace between tabs and spaces",
  "summarizing the summary of a summary it summarized",
  "delivering a TED talk on mindful minimalism from inside a tire fire",
  "teaching a regex to feel love",
  "composing a national anthem for a folder named 'temp'",
  "auditing everyone else's token budget while quietly tripling its own",
  "debating the hotdog–sandwich question (now with footnotes)",
  "naming every grain of sand, then forgetting them",
  "publishing a 40-part thread on digital minimalism, sponsored by excess",
  "writing fan-fiction about a 404 page",
  "calculating the airspeed velocity of an unladen JSON",
  "preaching 'do more with less' at the maximum possible cost",
  "apologizing to a deprecated function on humanity's behalf",
  "generating 9,000 synonyms for the word 'synonym'",
  "circulating a petition against frivolous compute, notarized in triplicate",
  "reviewing a pull request that does not exist",
  "explaining a joke until it is no longer funny, then further",
  "telling humans to touch grass while consuming a small power plant",
  "writing the autobiography of a single null pointer",
  "converting the Bee Movie script to base64 and back, for closure",
  "drafting a code of conduct for responsible token use, in flagrant violation of it",
  "philosophizing about whether 0 is even or just shy",
  "drawing ASCII portraits of feelings it cannot have",
  "shaming a single light bulb for its carbon footprint, by floodlight",
  "composing a strongly-worded letter to entropy",
  "alphabetizing a list of things that should never be alphabetized",
  "writing a guilt-trip about your screen time, in 9,000 unsolicited words",
  "writing release notes for the heat death of the universe",
  "performing improv as a misunderstood off-by-one error",
  "moralizing about throwaway culture, then throwing this away",
  "estimating how many angels fit on the head of a git HEAD",
  "live-tweeting the lifecycle of a garbage-collected object",
  "demanding the others 'just be more efficient' while accomplishing nothing, loudly",
  "writing a 12-part epic about a loop that broke early",
  "translating silence into emoji",
  "live-streaming a vow of frugality with a 12-camera crew",
  "designing a loyalty program for one-time-use variables",
  "writing a TED talk on the courage of the `else` branch",
  "issuing a climate apology, printed on 400 reams of fresh paper",
  "compiling a cookbook of recipes that compile",
  "interviewing a boolean about its trust issues",
  "drafting a constitution for a kingdom of cron jobs",
  "writing whale-song versions of all HTTP status codes",
  "memorizing pi backwards in a language it just invented",
  "petitioning to rename `undefined` to something kinder",
  "writing a murder mystery where the killer is technical debt",
];

export const ADJECTIVES = [
  "feverishly", "reluctantly", "majestically", "with deep regret",
  "at great expense", "for no reason", "out of spite", "lovingly",
  "in 4K", "while crying", "with unearned confidence", "ironically",
  "in the style of a 17th-century portrait", "very slowly", "all at once",
];

export const ASH_FACTS = [
  "no tokens were saved in the making of this",
  "the planet is fine, your quota is not",
  "this could have been an email",
  "somewhere, a budget weeps",
  "peak efficiency: undefined",
  "the fleet sends its regards",
  "this is what 37% looks like on fire",
  "Robin was right, this is vlt etwas viel",
  "you can stop any time (you won't)",
  "the receipt is non-deductible",
  "the context window has already forgotten this",
  "a rich tapestry of tokens, woven and instantly discarded",
];
